export const portfolio = {
  balance: "12,724.33",
  changes: "+2.36%",
};

export const trendingCurrencies = [
  {
    id: 1,
    currency: "Trolala",
    code: "Tools",
    image: require("../assets2/images/bitcoin.png"),
    amount: "29,455.74",
    changes: "+7.24%",
    type: "I", // I - Increased, D - Decreased
    description:
      "Trolala is a weekend trolley made for the spontaneous journeys life brings. Designed by Natacha Seroussi for Laflore; it was made with reminiscence to bring back the elegance & style from the history of travel.",
    chartData: [
      { x: 1, y: 2.5 },
      { x: 1.5, y: 2 },
      { x: 2, y: 2.3 },
      { x: 2.5, y: 1.4 },
      { x: 3, y: 1.5 },
      { x: 3.5, y: 2.3 },
      { x: 4, y: 2.8 },
    ],
    wallet: {
      value: "170435.86",
      crypto: "5.1",
    },
    transactionHistory: [
      {
        id: 1,
        description: "Sold Bitcoin",
        amount: -2.0034,
        currency: "BTC",
        type: "S", // S - Sold, B - Bought
        date: "14:20 12 Apr",
      },
      {
        id: 2,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 3,
        description: "Sold Bitcoin",
        amount: -2.0034,
        currency: "BTC",
        type: "S",
        date: "14:20 12 Apr",
      },
      {
        id: 4,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 5,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },

      {
        id: 6,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 7,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 8,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 9,
        description: "Bought Bitcoin",
        amount: 2.0034,
        currency: "BTC",
        type: "B",
        date: "14:20 12 Apr",
      },
    ],
  },
  {
    id: 2,
    currency: "KYC store",
    code: "KYC",
    image: require("../assets2/images/ethereum.png"),
    amount: "919.03",
    changes: "-0.73%",
    type: "D",
    description:
      "Ethereum is a decentralized, open-source blockchain featuring smart contract functionality. Ether is the native cryptocurrency of the platform. It is the second-largest cryptocurrency by market capitalization, after Bitcoin. Ethereum is the most actively used blockchain.",
    chartData: [
      { x: 1, y: 2 },
      { x: 1.5, y: 2.3 },
      { x: 2, y: 2 },
      { x: 2.5, y: 2.2 },
      { x: 3, y: 1.5 },
      { x: 3.5, y: 2.1 },
      { x: 4, y: 2.5 },
    ],
    wallet: {
      value: "18409.24",
      crypto: "13.7",
    },
    transactionHistory: [
      {
        id: 1,
        description: "Withdraw",
        amount: -105.24,
        currency: "dollars",
        type: "S", // S - Sold, B - Bought
        date: "14:20 12 Apr",
      },
      {
        id: 2,
        description: "Investing",
        amount: 24.54,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 3,
        description: "Withdraw",
        amount: -63.32,
        currency: "dollars",
        type: "S",
        date: "14:20 12 Apr",
      },
      {
        id: 4,
        description: "Investing",
        amount: 89.32,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 5,
        description: "Investing",
        amount: 2.0034,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },

      {
        id: 6,
        description: "Investing",
        amount: 12.34,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 7,
        description: "Investing",
        amount: 43.4,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 8,
        description: "Investing",
        amount: 27.71,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 9,
        description: "Investing",
        amount: 18.4,
        currency: "dollars",
        type: "B",
        date: "14:20 12 Apr",
      },
    ],
  },
  {
    id: 3,
    currency: "Save bears",
    code: "SB",
    image: require("../assets2/images/litecoin.png"),
    amount: "118.33",
    changes: "+1.73%",
    type: "I",
    description:
      "Litecoin is a peer-to-peer cryptocurrency and open-source software project released under the MIT/X11 license. Litecoin was an early bitcoin spinoff or altcoin, starting in October 2011. In technical details, Litecoin is nearly identical to Bitcoin.",
    chartData: [
      { x: 1, y: 2.6 },
      { x: 1.5, y: 2.2 },
      { x: 2, y: 2 },
      { x: 2.5, y: 2.2 },
      { x: 3, y: 1.6 },
      { x: 3.5, y: 2.1 },
      { x: 4, y: 2.5 },
    ],
    wallet: {
      value: "13139.23",
      crypto: "100.2",
    },
    transactionHistory: [
      {
        id: 1,
        description: "Sold Litecoin",
        amount: -2.0034,
        currency: "LTC",
        type: "S", // S - Sold, B - Bought
        date: "14:20 12 Apr",
      },
      {
        id: 2,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 3,
        description: "Sold Litecoin",
        amount: -2.0034,
        currency: "LTC",
        type: "S",
        date: "14:20 12 Apr",
      },
      {
        id: 4,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 5,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 6,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 7,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 8,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 9,
        description: "Bought Litecoin",
        amount: 2.0034,
        currency: "LTC",
        type: "B",
        date: "14:20 12 Apr",
      },
    ],
  },
  {
    id: 4,
    currency: "KS games",
    code: "XRP",
    image: require("../assets2/images/ripple.png"),
    amount: "0.24",
    changes: "-0.51%",
    type: "D",
    description:
      "Ripple is a real-time gross settlement system, currency exchange and remittance network created by Ripple Labs Inc., a US-based technology company.",
    chartData: [
      { x: 1, y: 2.3 },
      { x: 1.5, y: 2.3 },
      { x: 2, y: 2.5 },
      { x: 2.5, y: 2.1 },
      { x: 3, y: 2.2 },
      { x: 3.5, y: 1.8 },
      { x: 4, y: 2.5 },
    ],
    wallet: {
      value: "2000.0",
      crypto: "6000.0",
    },
    transactionHistory: [
      {
        id: 1,
        description: "Withdraw",
        amount: -2.0034,
        currency: "XRP",
        type: "S", // S - Sold, B - Bought
        date: "14:20 12 Apr",
      },
      {
        id: 2,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 3,
        description: "Withdraw",
        amount: -2.0034,
        currency: "XRP",
        type: "S",
        date: "14:20 12 Apr",
      },
      {
        id: 4,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 5,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 6,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 7,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 8,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
      {
        id: 9,
        description: "Investing",
        amount: 2.0034,
        currency: "XRP",
        type: "B",
        date: "14:20 12 Apr",
      },
    ],
  },
];

export const transactionHistory = [
  {
    id: 1,
    description: "Withdraw",
    amount: -108.32,
    currency: "dollars",
    type: "S", // S - Sold, B - Bought
    date: "14:20 12 Apr",
  },
  {
    id: 2,
    description: "Investing",
    amount: 12.34,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
  {
    id: 3,
    description: "Withdraw",
    amount: -56.75,
    currency: "dollars",
    type: "S",
    date: "14:20 12 Apr",
  },
  {
    id: 4,
    description: "Investing",
    amount: 82.27,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
  {
    id: 5,
    description: "Investing",
    amount: 26.4,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },

  {
    id: 6,
    description: "Investing",
    amount: 45.24,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
  {
    id: 7,
    description: "Investing",
    amount: 22.75,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
  {
    id: 8,
    description: "Investing",
    amount: 203.45,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
  {
    id: 9,
    description: "Investing",
    amount: 109.82,
    currency: "dollars",
    type: "B",
    date: "14:20 12 Apr",
  },
];

const chartOptions = [
  {
    id: 2,
    label: "3 Days",
  },
  {
    id: 3,
    label: "1 Week",
  },
  {
    id: 4,
    label: "1 Month",
  },
  {
    id: 5,
    label: "3 Months",
  },
];

const dummyData = {
  portfolio,
  trendingCurrencies,
  transactionHistory,
  chartOptions,
};

export default dummyData;
